- name: install the nginx 
  ansible.builtin.dnf: # ansible nginx dnf.  even we can use ansible.buitin.package
    name: nginx
    state: present

- name: enable and start the nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: include common role
  include_role:
    name: common
    # tasks_from: main 

# - name: delete html directory 
#   ansible.builtin.file:  # ansible html directory deletetml
#     path: /usr/share/nginx/html
#     state: absent

# - name: create html directory
#   ansible.builtin.file:  # ansible html directory delete
#     path: /usr/share/nginx/html 
#     state: directory

# - name: download frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: unzip frontend code
#   ansible.builtin.unarchive: #unzip file ansible
#     src: /tmp/frontend.zip
#     dest:  /usr/share/nginx/html
#     remote_src: yes # if backend code is not their in ansible and it is their remote machine(other location then ansible)

- name: copy expense config
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx
